---
title: "502 Project EDA"
author: "Madeline Chang"
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(dplyr)
library(forcats)
library(ggplot2)
library(rpart)
library(caret)
library(rpart.plot)
library(C50)
library(Metrics)
library(e1071)
library(glmnet)
```

Reading in data

```{r}
recruitment<- read.csv('/Users/mtc/ADS/ADS 502/Project/recruitment_data.csv')

recruitment<- recruitment %>%
  mutate(Gender = as.factor(Gender),
         EducationLevel = as.factor(EducationLevel),
         RecruitmentStrategy = as.factor(RecruitmentStrategy),
         HiringDecision = as.factor(HiringDecision),
         Gender_name = as.factor(ifelse(Gender == 0, "Male", "Female")),
         Hiring_name = as.factor(ifelse(HiringDecision == 0, "Not_Hired", "Hired")),
         Recruitment_name = fct_collapse(RecruitmentStrategy,
                                        Aggressive = 1,
                                        Moderate = 2,
                                        Conservative = 3),
         Education_name = fct_collapse(EducationLevel,
                                       Bachelor_1 = 1,
                                       Bachelor_2 = 2,
                                       Masters = 3,
                                       PhD = 4))
```

Data Quality

```{r}
colSums(is.na(recruitment))
```

```{r}
near_zero<- nearZeroVar(recruitment) # no columns with zero or near-zero variance

corr<- cor(recruitment[,c(1, 4, 5, 6, 7, 8, 9)])
high_corr <- findCorrelation(corr, cutoff = 0.75) # no numeric columns with high correlation with each other
```


Distribution of Variables

```{r}
hist<- function(col, bin_num){
  ggplot(data = recruitment) +
    geom_histogram(aes(x = .data[[col]]), bins = bin_num) +
    xlab(col)
}


hist("Age", 20)
hist("ExperienceYears", 15)
hist("PreviousCompanies", 5)
hist("DistanceFromCompany", 30)
hist("InterviewScore", 25)
hist("SkillScore", 25)
hist("PersonalityScore", 25)
```

```{r}
bar<- function(col){
  ggplot(data = recruitment) +
    geom_bar(aes(x = .data[[col]])) +
    xlab(col)
}

bar("Gender_name")
bar("Education_name")
bar("Recruitment_name")
bar("Hiring_name")
```

```{r}
ggplot(data = recruitment) +
  geom_bar(aes(x = Recruitment_name, fill = Hiring_name))

ggplot(data = recruitment) +
  geom_bar(aes(x = Hiring_name, fill = Gender_name))

ggplot(data = recruitment) +
  geom_bar(aes(x = Hiring_name, fill = Education_name))
```

```{r}
hiring_point<- function(x, y){
  ggplot(data = recruitment) +
    geom_point(aes(x = .data[[x]], y = .data[[y]], color = Hiring_name))
}

hiring_point("SkillScore", "PersonalityScore")
hiring_point("SkillScore", "InterviewScore")
```


```{r}
ggplot(data = recruitment) +
  geom_point(aes(x = SkillScore, y = InterviewScore, color = Gender_name))+
  facet_grid(~Hiring_name)

ggplot(data = recruitment) +
  geom_point(aes(x = SkillScore, y = PersonalityScore, color = Hiring_name)) +
  facet_grid(~Gender_name)
```

```{r}
set.seed(720)

trainingRows <- createDataPartition(recruitment$Hiring_name, p = .75, list = FALSE) 

recruit_train <- recruitment[trainingRows, ]
recruit_test <- recruitment[-trainingRows, ]
```

```{r}
log_reg<- glm(HiringDecision ~ Age + Gender + EducationLevel + ExperienceYears + PreviousCompanies + DistanceFromCompany + InterviewScore + SkillScore + PersonalityScore + RecruitmentStrategy, data = recruit_train, family = "binomial")

summary(log_reg)
```

Combine both bachelors degrees into one level- not statistically significant
No need for age or gender (seen in EDA), previous companies and distance are not statistically significant.

