---
title: "502 Project, Cross-Validation Setup"
author: "Madeline Chang"
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(dplyr)
library(forcats)
library(ggplot2)
library(rpart)
library(caret)
library(rpart.plot)
library(C50)
library(Metrics)
library(e1071)
library(glmnet)
library(nnet)
library(NeuralNetTools)
library(fastDummies)
library(class)
library(naivebayes)
```

Reading in data

```{r}
recruitment<- read.csv('/Users/mtc/ADS/ADS 502/Project/recruitment_data.csv')

recruitment<- recruitment %>%
  mutate(Gender = as.factor(Gender),
         EducationLevel = as.factor(EducationLevel),
         RecruitmentStrategy = as.factor(RecruitmentStrategy),
         HiringDecision = as.factor(HiringDecision),
         Gender_name = as.factor(ifelse(Gender == 0, "Male", "Female")),
         Hiring_name = as.factor(ifelse(HiringDecision == 0, "Not_Hired", "Hired")),
         Recruitment_name = fct_collapse(RecruitmentStrategy,
                                        Aggressive = 1,
                                        Moderate = 2,
                                        Conservative = 3),
         Education_name = fct_collapse(EducationLevel,
                                       Bachelors = 1,
                                       Bachelor_2 = 2,
                                       Masters = 3,
                                       PhD = 4))
```

### Splitting Data

```{r}
set.seed(720)

trainingRows <- createDataPartition(recruitment$Hiring_name, p = .75, list = FALSE) 

recruit_train <- recruitment[trainingRows, c(1, 4, 5, 6, 7, 8, 9, 12, 14, 15, 13)]
recruit_test <- recruitment[-trainingRows, c(1, 4, 5, 6, 7, 8, 9, 12, 14, 15, 13)]
```

### Creating Dummy Variables for Categorical Attributes

```{r}
non_num_train<- recruit_train %>%
  select(Gender_name, Education_name, Recruitment_name) %>%
  dummy_cols() %>%
  select(-c(1:3))

colnames(non_num_train)<- c("Female", "Male", "Bachelors1", "Bachelors2", "Masters", "PhD", "Agressive", "Moderate", "Conservative")

non_num_test<- recruit_test %>%
  select(Gender_name, Education_name, Recruitment_name) %>%
  dummy_cols() %>%
  select(-c(1:3))

colnames(non_num_test)<- c("Female", "Male", "Bachelors1", "Bachelors2", "Masters", "PhD", "Agressive", "Moderate", "Conservative")
```

### Combining Numeric and Dummy Variables into Train/Test Sets

```{r}
recruit_train_n<- non_num_train %>%
  cbind(recruit_train[,c(1, 2, 3, 4, 5, 6, 7)], recruit_train$Hiring_name) %>%
  rename(HiringDecision = "recruit_train$Hiring_name") 

recruit_test_n<- non_num_test %>%
  cbind(recruit_test[,c(1, 2, 3, 4, 5, 6, 7)], recruit_test$Hiring_name) %>%
  rename(HiringDecision = "recruit_test$Hiring_name") 
```

### Model Building Function

```{r}
ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

class_function<- function(method){
  model<- train(x = recruit_train_n[,1:16], 
               y = recruit_train_n$HiringDecision,
               method = method,
               preProc = c("center", "scale"),
               metric = "ROC",
               trControl = ctrl)
}
```

## Modeling

### Logistic Regression

```{r}
set.seed(720)
glm_train<- class_function("glm")
```

```{r}
glm_pred<- predict(glm_train, recruit_test_n)

conf<- data.frame(pred = glm_pred, actual = recruit_test_n$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```

### Naive Bayes

```{r}
set.seed(720)
nb_train<- class_function("naive_bayes")
```

```{r}
nb_pred<- predict(nb_train, recruit_test_n)

conf<- data.frame(pred = nb_pred, actual = recruit_test_n$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```

### KNN Model

```{r}
set.seed(720)
knn_train<- class_function("knn")
```

```{r}
knn_pred<- predict(knn_train, recruit_test_n)

conf<- data.frame(pred = knn_pred, actual = recruit_test_n$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```

### Neural Network Model

```{r}
set.seed(720)
nnet_train<- class_function("nnet")
```

```{r}
nnet_pred<- predict(nnet_train, recruit_test_n)

conf<- data.frame(pred = nnet_pred, actual = recruit_test_n$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```


