---
title: "502 Project Initial Modeling"
author: "Madeline Chang"
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(dplyr)
library(forcats)
library(ggplot2)
library(rpart)
library(caret)
library(rpart.plot)
library(C50)
library(Metrics)
library(e1071)
library(glmnet)
library(nnet)
library(NeuralNetTools)
library(fastDummies)
library(class)
```

Reading in data

```{r}
recruitment<- read.csv('/Users/mtc/ADS/ADS 502/Project/recruitment_data.csv')

recruitment<- recruitment %>%
  mutate(Gender = as.factor(Gender),
         EducationLevel = as.factor(EducationLevel),
         RecruitmentStrategy = as.factor(RecruitmentStrategy),
         HiringDecision = as.factor(HiringDecision),
         Gender_name = as.factor(ifelse(Gender == 0, "Male", "Female")),
         Hiring_name = as.factor(ifelse(HiringDecision == 0, "Not Hired", "Hired")),
         Recruitment_name = fct_collapse(RecruitmentStrategy,
                                        Aggressive = 1,
                                        Moderate = 2,
                                        Conservative = 3),
         Education_name = fct_collapse(EducationLevel,
                                       Bachelors = 1,
                                       Bachelor_2 = 2,
                                       Masters = 3,
                                       PhD = 4))
```

### Splitting Data

```{r}
set.seed(720)

trainingRows <- createDataPartition(recruitment$Hiring_name, p = .75, list = FALSE) 

recruit_train <- recruitment[trainingRows, ]
recruit_test <- recruitment[-trainingRows, ]
```

### Dummy Variables for Neural Network

```{r}
non_num_train<- recruit_train %>%
  select(Gender_name, Education_name, Recruitment_name) %>%
  dummy_cols() %>%
  select(-c(1:3))

colnames(non_num_train)<- c("Female", "Male", "Bachelors1", "Bachelors2", "Masters", "PhD", "Agressive", "Moderate", "Conservative")

non_num_test<- recruit_test %>%
  select(Gender_name, Education_name, Recruitment_name) %>%
  dummy_cols() %>%
  select(-c(1:3))

colnames(non_num_test)<- c("Female", "Male", "Bachelors1", "Bachelors2", "Masters", "PhD", "Agressive", "Moderate", "Conservative")
```


```{r}
min_max<- function(col){
  new = (col - min(col, na.rm = TRUE))/(max(col, na.rm = TRUE)-min(col, na.rm = TRUE))
}

numeric_train<- recruit_train[,c(1, 4, 5, 6, 7, 8, 9)]

nnet_scale_train<- data.frame(sapply(numeric_train, min_max))

colnames(nnet_scale_train)<- c("Age", "Previous_experience", "Previous_companies", "Distance", "Interview", "Skill", "Personality")

nnet_train<- nnet_scale_train %>%
  cbind(non_num_train, recruit_train$Hiring_name) %>%
  rename(HiringDecision = "recruit_train$Hiring_name")
```

```{r}
numeric_test<- recruit_test[,c(1, 4, 5, 6, 7, 8, 9)]

nnet_scale_test<- data.frame(sapply(numeric_test, min_max))

colnames(nnet_scale_test)<- c("Age", "Previous_experience", "Previous_companies", "Distance", "Interview", "Skill", "Personality")

nnet_test<- nnet_scale_test %>%
  cbind(non_num_test, recruit_test$Hiring_name) %>%
  rename(HiringDecision = "recruit_test$Hiring_name")
```

### Neural Network using nnet package

```{r}
set.seed(720)

nnet_01<- nnet(HiringDecision ~ ., data = nnet_train, size = 3)

plotnet(nnet_01)
```

```{r}
pred<- predict(nnet_01, nnet_test[,1:16], type = "class")

conf<- data.frame(pred = pred, actual = nnet_test$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```

### Scaling (Mean + SD) for KNN

```{r}
numeric_train<- recruit_train[,c(1, 4, 5, 6, 7, 8, 9)]

knn_scale_train<- data.frame(sapply(numeric_train, scale))

colnames(knn_scale_train)<- c("Age", "Previous_experience", "Previous_companies", "Distance", "Interview", "Skill", "Personality")

knn_train<- knn_scale_train %>%
  cbind(non_num_train, recruit_train$Hiring_name) %>%
  rename(HiringDecision = "recruit_train$Hiring_name")
```

```{r}
numeric_train<- recruit_train[,c(1, 4, 5, 6, 7, 8, 9)]

knn_scale_test<- data.frame(sapply(numeric_test, scale))

colnames(knn_scale_test)<- c("Age", "Previous_experience", "Previous_companies", "Distance", "Interview", "Skill", "Personality")

knn_test<- knn_scale_test %>%
  cbind(non_num_test, recruit_test$Hiring_name) %>%
  rename(HiringDecision = "recruit_test$Hiring_name")
```


```{r}
knn_pred<- knn(knn_train[,1:16], knn_test[,1:16], knn_train$HiringDecision, k = 10)

conf<- data.frame(pred = knn_pred, actual = knn_test$HiringDecision) %>%
  mutate(actual = as.factor(actual),
         pred = as.factor(pred))

cm<- confusionMatrix(conf$actual, conf$pred)
cm
```

